title: Project

columns:
  - width: 1/3
    sections:
      info:
        type: fields
        fields:
          thumbnail:
            label: Thumbnail in project menu
            type: files
            min: 1
            max: 1
          quote: 
            type: text
          