title: Project

columns:
  - width: 1/2
    sections:
      media:
        type: fields
        fields:
          thumbnail:
            label: Thumbnail in project menu
            type: files
            min: 1
            max: 1
          carousel:
            label: Carousel images
            type: files
            multiple: true
            layout: cards # options: cards, list, or table for display style in the panel
            image:
              cover: true # ensures the images are displayed as cover
              ratio: 3/2  # sets the aspect ratio for previews in the panel (optional)
            uploads:
              template: image # ensure only images can be uploaded
            help: "Upload multiple images to create a gallery."
          
  - width: 1/2
    sections:
      info:
        type: fields
        fields: 
          description: 
            label: Project text
            type: textarea
          quote: 
            type: text
          video:
            label: Video url 
            type: url
          credits:
            label: credits
            type: structure
            fields:
              role:
                label: role
                type: text
              people:
                label: people
                type: text
          related:
            label: Related Pages
            type: pages
              