# The `site.yml` blueprint defines the look of the start page (Dashboard) of the Panel.

# The site blueprint usually provides easy access to all main pages of the site.
# In this example blueprint, we also show subpages of the `photography` and `notes` pages.
# More about the site blueprint: https://getkirby.com/docs/reference/panel/blueprints/site

# The layout of this form has two columns:
columns:
  # The first column has one section for the subpages of the `photography` page in card layout
  # It reuses the pages section defined in `/site/blueprints/sections/albums.yml`
  - width: 1/2
    sections:
      pages:
        type: pages
        create: default
        templates:
          - about
          - home
          - default
          - projects
          - project
          - topics
          - donation
          - contact
          - articles
  - width: 1/2 
    sections: 
      contact: 
        type: fields
        fields:
          socialLinks:
            label: Social Links
            type: structure
            help: Add social media links that will be displayed in footer
            fields:
              platform:
                label: Platform
                type: text
              url:
                label: URL
                type: url
          email: 
            label: Email
            type: email
      bankDetails: 
        type: fields
        fields: 
          accountName: 
            label: Account name 
            type: text
          iban: 
            label: IBAN
            type: text
          bic: 
            label: BIC
            type: text
          adress: 
            label: adress
            type: text

          



        

